//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Books.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الحدث.
        /// </summary>
        public static string ActionDate {
            get {
                return ResourceManager.GetString("ActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحدث.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل المستحدم.
        /// </summary>
        public static string activeUser {
            get {
                return ResourceManager.GetString("activeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم جديد.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   تم الحذف بنجاح.
        /// </summary>
        public static string alertDeleteContent {
            get {
                return ResourceManager.GetString("alertDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل بالتاكيد تريد الحذف بالفعل؟.
        /// </summary>
        public static string alertDeleteContentCheck {
            get {
                return ResourceManager.GetString("alertDeleteContentCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string alertDeleteTitle {
            get {
                return ResourceManager.GetString("alertDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسنا.
        /// </summary>
        public static string alertOK {
            get {
                return ResourceManager.GetString("alertOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة المرور.
        /// </summary>
        public static string btnChangePassword {
            get {
                return ResourceManager.GetString("btnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة الفئات .
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات الفئات.
        /// </summary>
        public static string CategoriesLog {
            get {
                return ResourceManager.GetString("CategoriesLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الفئة.
        /// </summary>
        public static string CategoryDescription {
            get {
                return ResourceManager.GetString("CategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانيات المستخدم.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ البيانيات.
        /// </summary>
        public static string errorMsgContent {
            get {
                return ResourceManager.GetString("errorMsgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الحفظ.
        /// </summary>
        public static string errorMsgTitle {
            get {
                return ResourceManager.GetString("errorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string errorType {
            get {
                return ResourceManager.GetString("errorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك اي صلاحية لفعل هذه العملية.
        /// </summary>
        public static string lbMsgDenied {
            get {
                return ResourceManager.GetString("lbMsgDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاكد من كلمة المرور او البريد الاكنروني .
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة المرور.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاكيد كلمة المرور.
        /// </summary>
        public static string RegisterConfirmpassword {
            get {
                return ResourceManager.GetString("RegisterConfirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الاكنروني.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Registerpassword {
            get {
                return ResourceManager.GetString("Registerpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحداث.
        /// </summary>
        public static string RolesActions {
            get {
                return ResourceManager.GetString("RolesActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مجموعة جديدة.
        /// </summary>
        public static string RolesAddRole {
            get {
                return ResourceManager.GetString("RolesAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل مجموعة المستخدمين.
        /// </summary>
        public static string RolesBigTitle {
            get {
                return ResourceManager.GetString("RolesBigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string RolesBtnDelete {
            get {
                return ResourceManager.GetString("RolesBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string RolesBtnEdit {
            get {
                return ResourceManager.GetString("RolesBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string RolesCancelRole {
            get {
                return ResourceManager.GetString("RolesCancelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        public static string RolesGroupName {
            get {
                return ResourceManager.GetString("RolesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة  الرئسية .
        /// </summary>
        public static string RolesHomePage {
            get {
                return ResourceManager.GetString("RolesHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الكتب.
        /// </summary>
        public static string RolesManageBooks {
            get {
                return ResourceManager.GetString("RolesManageBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة المستخدمين.
        /// </summary>
        public static string RolesMidTitle {
            get {
                return ResourceManager.GetString("RolesMidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string RolesSaveRole {
            get {
                return ResourceManager.GetString("RolesSaveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ البيانيات بنجاح.
        /// </summary>
        public static string saveMsgContent {
            get {
                return ResourceManager.GetString("saveMsgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه الفئة موجودة بالفعل.
        /// </summary>
        public static string saveMsgContentDublict {
            get {
                return ResourceManager.GetString("saveMsgContentDublict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ.
        /// </summary>
        public static string saveMsgTitle {
            get {
                return ResourceManager.GetString("saveMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة فئة جديدة.
        /// </summary>
        public static string SaveNewCategory {
            get {
                return ResourceManager.GetString("SaveNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---اختر اسم المجموعة---.
        /// </summary>
        public static string SelectGroupName {
            get {
                return ResourceManager.GetString("SelectGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string successType {
            get {
                return ResourceManager.GetString("successType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الفئة.
        /// </summary>
        public static string TitleEditCategory {
            get {
                return ResourceManager.GetString("TitleEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل البيانيات بنجاح.
        /// </summary>
        public static string updateMsgContent {
            get {
                return ResourceManager.GetString("updateMsgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم البيانيات .
        /// </summary>
        public static string updateMsgContentError {
            get {
                return ResourceManager.GetString("updateMsgContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string updateMsgTitle {
            get {
                return ResourceManager.GetString("updateMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل التعديل.
        /// </summary>
        public static string updateMsgTitleError {
            get {
                return ResourceManager.GetString("updateMsgTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  صورة المستحدم  .
        /// </summary>
        public static string UserImage {
            get {
                return ResourceManager.GetString("UserImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين الحالين .
        /// </summary>
        public static string UsersBigTitle {
            get {
                return ResourceManager.GetString("UsersBigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعات المستخدمين.
        /// </summary>
        public static string usersGroups {
            get {
                return ResourceManager.GetString("usersGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة المستخدمين.
        /// </summary>
        public static string UsersHomePage {
            get {
                return ResourceManager.GetString("UsersHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ادارة المستخدمين.
        /// </summary>
        public static string UsersManage {
            get {
                return ResourceManager.GetString("UsersManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string UsersSaveBtn {
            get {
                return ResourceManager.GetString("UsersSaveBtn", resourceCulture);
            }
        }
    }
}
